############################
# --- Required options --- #
############################

title: Anup Yadav
share-title: From Supply Chain to Data Science
meta-description: I’m Anup Yadav — a data-driven professional working at Zomato (Hyperpure), with expertise in supply chain, operations, and analytics. I'm currently transitioning into a full-time data analyst role by building a portfolio of real-world insights.

author: Anup Yadav

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  Projects: "projects"
  About Me: "aboutme"
  Resume: "resume/Anup_Yadav_Resume.pdf"

################
# --- Logo --- #
################

avatar: "/assets/img/anup.jpg"
round-avatar: true

#####################################
# --- Footer social media links --- #
#####################################

social-network-links:
  github: yourgithubusername
  linkedin: yourlinkedinid
  twitter: yourtwitterhandle
  instagram: yourinsta
  email: your.email@example.com
  rss: false

rss-description: Data, insights, and decisions — my digital notebook.

###########################
# --- General options --- #
###########################

share-links-active:
  twitter: true
  facebook: false
  linkedin: true
  vk: false

url-pretty: "anuptyadav.dev"
title-on-all-pages: true
title-off-on-page: false
excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
post_search: false
edit_page_button: false
navbar-var-length: true

keywords: "anup yadav, data analyst, business analyst, supply chain, warehouse analytics, Zomato, Hyperpure, SQL, Python, Power BI, data science, operations, analytics portfolio, Excel"

######################################
# --- Colours / background image --- #
######################################

page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#890000"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#890000"
mobile-theme-col: "#a50509"

#################################
# --- Web Analytics Section --- #
#################################

# Remove if not needed
gtag: "G-XXXXXXXXXX"

####################
# --- Comments --- #
####################

disqus: "anuptyadav"

################
# --- Misc --- #
################

title-separator: "-"
date_format: "%B %-d, %Y"
timezone: "Asia/Kolkata"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
      readtime: true
  -
    scope:
      path: ""
    values:
      layout: "page"

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
